import type { WeaponDefinition } from '../types';

// 原创武器配置表 - 名称、外观均为原创，避免复制现有游戏
export const WEAPONS: WeaponDefinition[] = [
  {
    id: 'basic_shell',
    displayName: '星火榴弹',
    description: '平衡的单发炮弹，伤害与爆炸半径中等。',
    ammo: -1, // -1 表示无限
    projectileCount: 1,
    projectileSpeedMultiplier: 1,
    gravityMultiplier: 1,
    windMultiplier: 1,
    explosionRadius: 52,
    maxDamage: 42,
    terrainDamageMultiplier: 1,
    behavior: 'standard',
    color: '#ffd166',
  },
  {
    id: 'triple_scatter',
    displayName: '岚羽三联弹',
    description: '同时发射三枚炮弹，单发伤害较低但覆盖面广。',
    ammo: 6,
    projectileCount: 3,
    projectileSpeedMultiplier: 1,
    gravityMultiplier: 1,
    windMultiplier: 1,
    explosionRadius: 38,
    maxDamage: 22,
    terrainDamageMultiplier: 0.9,
    spreadAngle: 8,
    behavior: 'standard',
    color: '#f4a261',
  },
  {
    id: 'air_split',
    displayName: '棱镜裂空弹',
    description: '飞行一段时间后在空中分裂成多枚子弹。',
    ammo: 5,
    projectileCount: 1,
    projectileSpeedMultiplier: 1,
    gravityMultiplier: 1,
    windMultiplier: 1,
    explosionRadius: 34,
    maxDamage: 18,
    terrainDamageMultiplier: 0.85,
    splitTime: 0.9,
    childCount: 4,
    childSpeed: 140,
    behavior: 'split',
    color: '#a8dadc',
  },
  {
    id: 'bounce_shot',
    displayName: '青跃弹',
    description: '首次触地后会反弹，最多反弹 3 次后爆炸。',
    ammo: 5,
    projectileCount: 1,
    projectileSpeedMultiplier: 1,
    gravityMultiplier: 1,
    windMultiplier: 0.8,
    explosionRadius: 44,
    maxDamage: 36,
    terrainDamageMultiplier: 0.9,
    bounceCount: 3,
    bounceRestitution: 0.55,
    behavior: 'bounce',
    color: '#90be6d',
  },
  {
    id: 'drill_shot',
    displayName: '紫牙钻地弹',
    description: '接触地形后继续向内部钻进一段距离后爆炸，制造深坑。',
    ammo: 4,
    projectileCount: 1,
    projectileSpeedMultiplier: 1,
    gravityMultiplier: 1.1,
    windMultiplier: 0.6,
    explosionRadius: 46,
    maxDamage: 44,
    terrainDamageMultiplier: 1.4,
    drillDistance: 30,
    behavior: 'drill',
    color: '#9d4edd',
  },
  {
    id: 'heavy_impact',
    displayName: '陨铁重锤',
    description: '伤害与爆炸范围都较大，弹道更低，弹药稀少。',
    ammo: 3,
    projectileCount: 1,
    projectileSpeedMultiplier: 0.85,
    gravityMultiplier: 1.25,
    windMultiplier: 0.7,
    explosionRadius: 74,
    maxDamage: 62,
    terrainDamageMultiplier: 1.25,
    behavior: 'heavy',
    color: '#ef476f',
  },
  {
    id: 'micro_cluster',
    displayName: '萤雨集束弹',
    description: '主弹在空中爆开并向下释放数枚小子弹。',
    ammo: 4,
    projectileCount: 1,
    projectileSpeedMultiplier: 1,
    gravityMultiplier: 1,
    windMultiplier: 0.6,
    explosionRadius: 26,
    maxDamage: 14,
    terrainDamageMultiplier: 0.7,
    splitTime: 0.7,
    childCount: 5,
    childSpeed: 150,
    behavior: 'cluster',
    color: '#06d6a0',
  },
  {
    id: 'aurora_needle',
    displayName: '极光穿针',
    description: '高速、低风偏的小范围精确弹，直接命中伤害极高。',
    ammo: 4,
    projectileCount: 1,
    projectileSpeedMultiplier: 1.35,
    gravityMultiplier: 0.72,
    windMultiplier: 0.3,
    explosionRadius: 24,
    maxDamage: 70,
    terrainDamageMultiplier: 0.35,
    behavior: 'standard',
    color: '#7df9ff',
  },
  {
    id: 'tide_stream',
    displayName: '潮汐流束',
    description: '六枚炮弹沿同一方向以不同速度连续排开。',
    ammo: 4,
    projectileCount: 6,
    projectileSpeedMultiplier: 1,
    projectileSpeedStep: 0.065,
    gravityMultiplier: 1,
    windMultiplier: 0.85,
    explosionRadius: 25,
    maxDamage: 13,
    terrainDamageMultiplier: 0.55,
    spreadAngle: 0,
    behavior: 'standard',
    color: '#48cae4',
  },
  {
    id: 'stone_runner',
    displayName: '岩轨滚轮',
    description: '落地后沿地表向前滚动，接触坦克或耗尽距离时爆炸。',
    ammo: 4,
    projectileCount: 1,
    projectileSpeedMultiplier: 0.9,
    gravityMultiplier: 1.05,
    windMultiplier: 0.65,
    explosionRadius: 42,
    maxDamage: 40,
    terrainDamageMultiplier: 0.8,
    rollDistance: 260,
    rollSpeed: 135,
    behavior: 'roller',
    color: '#ff9f1c',
  },
  {
    id: 'sky_coordinates',
    displayName: '天穹坐标弹',
    description: '标记落点后，从高空呼叫五枚小型炮弹纵向齐射。',
    ammo: 3,
    projectileCount: 1,
    projectileSpeedMultiplier: 1,
    gravityMultiplier: 1,
    windMultiplier: 0.8,
    explosionRadius: 30,
    maxDamage: 19,
    terrainDamageMultiplier: 0.65,
    airstrikeCount: 5,
    airstrikeSpread: 42,
    behavior: 'airstrike',
    color: '#ff70a6',
  },
];

export function getWeaponById(id: string): WeaponDefinition {
  const w = WEAPONS.find((x) => x.id === id);
  if (!w) return WEAPONS[0];
  return w;
}
